from enum import IntEnum

MAGIC = 0x59474631  # 'YGF1' big-endian: Yugoef Frame v1
PROTOCOL_VERSION = 1
ENDIANNESS = "big"
HEADER_LENGTH = 40
CRC_LENGTH = 4
AUTH_FLAG = 0x01
AUTH_TAG_LENGTH = 16
MAX_PACKET_SIZE = 1400
MAX_PAYLOAD_LENGTH = MAX_PACKET_SIZE - HEADER_LENGTH - CRC_LENGTH
MAX_SUBCARRIERS = 256
MAX_ANTENNAS = 4
UINT32_MAX = 0xFFFFFFFF


class MessageType(IntEnum):
    NODE_HELLO = 1
    RAW_CSI = 2
    HEARTBEAT = 3
    CONFIG = 4
    CONFIG_ACK = 5
    ERROR = 6
